name: Verificar novas publicações

on:
  schedule:
    - cron: "*/30 * * * *"    # a cada 30m
  workflow_dispatch:          # roda manualmente, se quiser

jobs:
  monitorar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run monitor script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python monitor.py

      - name: Commit da nova data (se houver)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add ultima_data.txt
          git diff --cached --quiet || git commit -m "Atualiza ultima_data.txt"
          git push
